### ISSUE TITLE
On outputs.tf, set the output values to be sensitive

### ISSUE THREAD

**Issue by jross-ai** [cloudposse/terraform-aws-ssm-parameter-store#23]
## Describe the Feature

Set the output values to have the flag `sensitive = true` as part of the upgrade to terraform v14

## Expected Behavior

Terraform plan should succeed when sensitive variables are passed into the ssm parameter store module.

## Use Case

If one wants to pass sensitive values into the ssm parameter store module, then output values for the module need to have the sensitive flag.

## Describe Ideal Solution

Add the `sensitive = true` flag to the output values: names, values, map, arn_map

## Alternatives Considered

N/A

## Additional Context

As part of the upgrade to terraform v14, users are able to set variables to be sensitive so as to not show sensitive values in the plan output: https://www.terraform.io/upgrade-guides/0-14.html#sensitive-values-in-plan-output

**Comment by bmwosz** [comment]
I have created PR for this issue:
https://github.com/cloudposse/terraform-aws-ssm-parameter-store/pull/28

**Comment by wszychta** [comment]
Any updates on this issue?

**Comment by syphernl** [comment]
@wszychta @jross-ai In Terraform [0.15.0](https://github.com/hashicorp/terraform/releases/tag/v0.15.0) and [0.15.1](https://github.com/hashicorp/terraform/releases/tag/v0.15.1) a number of fixes & improvements have been done in regards to (handling of) sensitive values. 

In my case I was getting an error with `terraform-aws-ecs-web-app` before I upgraded to 0.15.1 (`Error: Output refers to sensitive values`) which is now working fine. 
The change of #28 might not be necessary anymore.

**Comment by rafaljanicki** [comment]
Hey,

It's still an issue with 0.15.3 version of Terraform, could we get the PR merged? It's a major blocker from using this module
