### ISSUE TITLE
Upgrade terraform version to ~> 0.14.0

### ISSUE THREAD

**Issue by cha7ri** [cloudposse/terraform-aws-ssm-parameter-store#31]
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Feature

Upgrade terraform version to `~> 0.14.0`

## Use Case

We depend on this module and we need to upgrade terraform version

**Comment by nitrocode** [comment]
Any terraform version above 0.13 can use this module. I don't fully understand the need to bump up the minimum version.

You can set a required_version in the root module and use one that's greater than that of this child module.

Please ping back if there is a better reason to upgrade the min tf version in this child module.
