### ISSUE TITLE
Template provider not being used in the code but it is listed in versions.tf

### ISSUE THREAD

**Issue by kfenech1** [cloudposse/terraform-aws-ssm-parameter-store#35]
## Describe the Bug
Template provider not being used in the code but it is listed in versions.tf This causes problems with ARM based machines since the template provider does not support ARM.

## Expected Behavior
Remove template from versions.tf since it is not used by this module.

**Comment by nitrocode** [comment]
@kfenech1 thanks for reporting. This was closed in this PR https://github.com/cloudposse/terraform-aws-ssm-parameter-store/pull/36
